# 2.14

class Solution:
    def max_profit(self, prices: list[int]) -> int:
        """Find the maximum profit generated by buying and selling one stock.

        Args:
            prices (list[int]): integer array representing the stock prices.

        Returns:
             int: maximum profit generated by buying and selling one stock.

        Time: O(n) - n = len(prices)

        Space: O(1)
        """

        max_profit = 0
        left = 0
        right = 1

        while right < len(prices):

            if prices[right] <= prices[left]:
                left = right
                right = left + 1
            else:
                curr_profit = prices[right] - prices[left]
                max_profit = max(max_profit, curr_profit)
                right += 1

        return max_profit

s = Solution()
print(s.max_profit(prices = [10,1,5,6,7,1]))
print(s.max_profit(prices = [10,8,7,5,2]))

# 2.26 -> 12 min