# 10.08

class Solution:
    def maxProfit(self, prices: list[int]) -> int:
        """Find maximum profit by buying and selling stocks.

        Args:
            prices: prices of stack for each day

        Returns:
            maximum profit generated by buying and selling stocks

        Time: O(n) - n = len(prices)
        Space: O(1)
        """
        max_profit = 0

        left = 0
        right = 1

        while right < len(prices):
            if prices[right] <= prices[left]:
                left = right
            else:
                curr_profit = prices[right] - prices[left]
                max_profit = max(max_profit, curr_profit)

            right += 1

        return max_profit

s = Solution()
assert s.maxProfit([7,1,5,3,6,4]) == 5
assert s.maxProfit([7,6,4,3,1]) == 0
assert s.maxProfit([]) == 0
assert s.maxProfit([5]) == 0
assert s.maxProfit([1,2,3,4,5]) == 4
print("passed")

# 10.13 -> 5 min to finish